log: # 日志配置
  # 日志路径
  dir: "./log"

redis:
  addr: 127.0.0.1:6379
  pasword: ""
  # 连接池大小
  poolSize: 10
  # 连接超时时间
  dialTimeout: 100ms
  # 读超时时间
  readTimeout: 500ms
  # 写超时时间
  writeTimeout: 300ms
